spring:
  datasource:
    url: jdbc:h2:mem:sdw2023
    username: sdw2023
    password: 1234
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create # validate | update | create | create-drop
    properties:
      hibernate:
        format_sql: true
#  security:
#    user:
#      name: user1
#      password: 1234
#      roles: USER
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

springdoc:
  swagger-ui:
    enabled: true
    title: API Documentation
    description: Documentação da API do sistema Avanade Decola
    version: 1.0.0
  packages-to-scan: netto.leonidas.avanade_decola.controller